version: '3.8'

services:
  face-recognition-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: face-recognition-server
    ports:
      - "3001:3001"
    environment:
      - SERVER_PORT=3001
      - SERVER_HOST=0.0.0.0
      - SERVER_LOG_LEVEL=info
      - SERVER_MODEL_PATH=model/insightface/
    volumes:
      - ./user_data.pkl:/app/user_data.pkl
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - face-compare-network

networks:
  face-compare-network:
    driver: bridge 